### ISSUE TITLE
Histogram plugin for Crystal Endcap Ecal algorithms

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#109]
Make plugin that produces histograms demonstrating each algorithm in the Crystal Encap Ecal mermaid plot form[ EICrecon issue #11](https://github.com/eic/EICrecon/issues/11) are working,

**Comment by faustus123** [comment]
The EEMCcheck plugin can serve this purpose, but needs to have additional histograms for the truth leg of the mermaid plot.

**Comment by torrijeske** [comment]
I suspect potential issues with the recoCoG portion-- EcalEndcapNClusters_hits_per_cluster fills with all 0s. 

trying to obtain the merged clusters produces the following:
[INFO] JWorker: Worker 0 shutdown due to JException: Could not find JFactoryT<edm4eic::MCRecoClusterParticleAssociation> with tag=EcalEndcapNClustersAssoc
[INFO] Status: 0 events processed  0.0 Hz (0.0 Hz avg)
[FATAL] Detected exception in worker! Re-throwing on main thread.
----------------------------------------------------------
Exception: Could not find JFactoryT<edm4eic::MCRecoClusterParticleAssociation> with tag=EcalEndcapNClustersAssoc
  Plugin:         CrystalEndcapEcalHistograms.so
  Component:      CrystalEndcapEcalHistogramsProcessor

**Comment by DraTeots** [comment]
I guess this should be closed now? Please reopen if I'm not right
