### ISSUE TITLE
Plugins to produce benchmark plots

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#125]
We need to implement at least one plugin that produces some simple benchmark plots demonstrating the reconstruction algorithms are working. These may also serve as basis for comparing different geometries.

These should be placed in something like "src/benchmarks/calorimetry_benchmark"

(C) David Lawrence

**Comment by DraTeots** [comment]
That is very relevant to what we all are doing right now. 

There are benchmarks for reconstruction and simulation 

https://eicweb.phy.anl.gov/EIC/benchmarks

Do I understand correctly that the benchmarks from this ticket is supposed to be more EICrecon and technical related. Or  are we going to partially/fully convert those into plugins?

**Comment by faustus123** [comment]
I would like to have some benchmarks in JANA plugins that can be generated during the simulation campaigns. The reasoning is:

1. They will be able to see intermediate objects that we may end up not writing to the output file
2. We will want something like this for online stream monitoring that does not require reading from files

The JANA plugins will supplement the offline benchmarks. I can see people being more attracted to those since they can just be root macros. Thus, the JANA plugins may not be as widely used as they are in GlueX where our raw simulated data and DSTs are not root files.
