### ISSUE TITLE
Demonstration of ML Integration in EICrecon

### ISSUE THREAD

**Issue by ruse-traveler** [eic/EICrecon#1340]
As of eic/containers#9 , TMVA::SOFIE is now included as part of eic-shell for ONNX support. However, as of the submitting of this issue, there are no examples in EICrecon/main demonstrating how to use this functionality.

**Describe the solution you'd like**
There have been several standalone studies of ePIC simulations which utilized ML in some capacity (e.g see [the ePIC AI/ML Town Hall](https://indico.bnl.gov/event/20374/) or  [AI4EIC 2023](https://indico.bnl.gov/event/19560/)), including many which would be good additions to our suite of reconstruction algorithms.

**Additional Context**
Support for ONNX/examples of how to use this in EICrecon was identified as one of the TDR wants from the calorimetry side.

**Comment by veprbl** [comment]
We still don't have onnxruntime for inference part https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/789
It's not clear (at least, to me) if TMVA is a good candidate for inference over PODIO objects. There was also some nice discussion about EDM changes needed to support consistent inputs between inference and training as well a report the correct labels https://chat.epic-eic.org/main/pl/hi7hf5dcepft9m9wsbd1fgiyzc

There is some work to be done on the training side. The idea is that, since we don't have a conditions database, we are using artifacts (e.g. stored in https://github.com/eic/epic-data) defined in epic geometry compact XML files. Those artifacts need to be reproducible to prevent black boxing. We want to have this working via CI, and work was started on this in https://github.com/eic/detector_benchmarks/pull/10 .
