### ISSUE TITLE
Total four-momentum of a calorimeter 

### ISSUE THREAD

**Issue by sebouh137** [eic/EICrecon#1496]
**Is your feature request related to a problem? Please describe.**
Need an algorithm that produces the total four momentum of all of the clusters in a calorimeter (for instance the HCal Insert, or the ZDC)

**Describe the solution you'd like**
New algorithm that adds up the four momenta of all clusters in the calorimeter, assuming they are from particles originating from the origin

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sebouh137** [comment]
This is a good question, and I plan to fulfill this feature myself.  I would like to output a single object representing the four momentum of the events, but if PODIO does not support outputing a four vector object I will create a ReconstructedParticle object instead.

**Comment by ruse-traveler** [comment]
Hmmm... So there are 4-vectors in the data model: e.g. see `edm4hep::Vector4f` [here](https://github.com/key4hep/EDM4hep/blob/0784e02caf09ee89a728b4dd17ed74ef082e4d66/edm4hep.yaml#L9)), but these aren't meant to be saved to a collection...

And `ReconstructedParticle` is a pretty heavy type for just a 4-vector, so my next question is what's it for? Is it for things like the neutron candidates in the ZDC?

**Comment by sebouh137** [comment]
The detector I have in mind for this is the forward HCAL insert, since a large amount of the transverse momentum and energy goes to that detector.  @ruse-traveler , let me know which data type you think is most appropriate for this.

**Comment by ruse-traveler** [comment]
It makes sense that a lot of pT ends up in the insert, but what are you going to _do_ with the total 4-momentum? For example, is it going to be used to determine the kinematics of a particular set of particles? Or is it going to be used to tag a particular final state?

Or is this a performance metric for the insert? In which case, I think this calculation would be better served as a detector benchmark...

I ask because I'm a bit confused about why this calculation needs a separate algorithm and to be persisted in a datatype... Could this be handled in analysis code downstream?

**Comment by sebouh137** [comment]
Hi Derek,
Thanks for the suggestion; we could use this algorithm in a detector benchmark.

**Comment by ruse-traveler** [comment]
Gotcha! Sounds good!
