### ISSUE TITLE
Add smearing to TrackParamTruthInit

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#215]
On behalf of @Simple-Shyam. Original message: 

```
It's giving an error. Can you please change the line in the correct format, the below line is giving an error.

    const auto phi_smear = phi + 0.20*gRandom->Gaus(0.,phi);
    const auto theta_smear = theta + 0.20*gRandom->Gaus(0.,theta);
    const auto pmag_true = pmag * GeV
    const auto pmag_smear = pmag_true + 0.20*gRandom->Gaus(0.,pmag_true);

I want to pass them like below

    Acts::BoundVector  params;
    params(Acts::eBoundLoc0)   = 0.0 * mm ;  // cylinder radius
    params(Acts::eBoundLoc1)   = 0.0 * mm ;  // cylinder length
    params(Acts::eBoundPhi)    = phi_smear;
    params(Acts::eBoundTheta)  = theta_smear;
    params(Acts::eBoundQOverP) = charge / (pmag_smear);
    params(Acts::eBoundTime)   = part->getTime() * ns;
```

The issue is actually: 

- [ ] update TrackParamTruthInitConfig and add smearing values (those 0.20)
- [ ] update TrackParamTruthInit_factory to add Smearing parameters so users can modify them

**Comment by Simple-Shyam** [comment]
Thanks, let me state the problem, the main issue is when we are fitting in ACTs, we need to pass parameters, which we are currently passing true parameters from MC. If you reconstruct, you will get true momentum (fitter is biased). We need to smear the initial true parameters so that fitter tries to minimize them. I put an example (just an example), we should smear with some numbers after discussion, how much smear we can put in the true parameters. We can follow similar as fun4all for smearing linked below.

https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc

**Comment by DraTeots** [comment]
Here is vtx smearing: 
https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc#L270

And guess here is the momentum smearing
https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc#L734

**Comment by Simple-Shyam** [comment]
Thanks, Yes  also theta and Phi. I will check and understand and will confirm (our colleagues in Bari) it in coming days then that will fix the issue.

**Comment by DraTeots** [comment]
The smearing is not needed as experts agreed.
