### ISSUE TITLE
Missing plugin dependencies

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#230]
EICrecon does not specify dependencies between the libraries correctly.

Building on macOS leads to linker errors due to undefined symbols, as ld64 doesn't allow that by default.

This can be reproduced with binutils on Linux `LDFLAGS=-Wl,--no-undefined`. Here is a build log:
https://gist.github.com/veprbl/c1512e87438c43449923803aa17d8d44

Runtime error on Linux:
```
[ERROR] JPluginLoader: Couldn't load plugin 'acts.so'
  Make sure that JANA_HOME and/or JANA_PLUGIN_PATH environment variables are set correctly.
  Paths checked:
    .../lib/EICrecon/plugins/dd4hep.so  =>  Loaded successfully
    .../lib/EICrecon/plugins/acts.so  =>  Loading failure: .../lib/EICrecon/plugins/acts.so: undefined symbol: _ZN11Log_service6loggerERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
    ./acts.so  =>  File not found
    .../plugins/acts.so  =>  File not found

[FATAL] Exception: Couldn't find plugin 'acts.so'
```

**Comment by DraTeots** [comment]
Confirm. Fixing

**Comment by veprbl** [comment]
Oh, and there will be ~~dragons~~cyclical dependencies too.

**Comment by nathanwbrei** [comment]
@DraTeots Keep me in the loop on this one

**Comment by DraTeots** [comment]
I believe today in the morning I was young and naive thinking that I quickly fix all the issues. 

The PR does a lot of cleanup and speedup for CMake that was in plans for a while. It should also ~kill dragons~ remove some cyclic dependencies. 

But in the end of the day, when I became old and wise, I'm not sure it is possible to compile everything with `--no-undefined` because of the dynamic idea of plugins, that are dlopen-ed depending on user parameters. So...

1. Please try the changes by this PR
2. Maybe @faustus123 could help with MAC. Unfortunately I don't have ability to try and experience here. 
3. Could we point out ~where live the dragons~ what cyclic dependencies we talk about . Because I know at least one place where it exist and is difficult to exterminate for stupid historical reasons.

**Comment by faustus123** [comment]
@DraTeots is correct that because some things depend on services coming from other plugins, the order in which they are dlopen'd matters. Thus, the order that the plugins are listed matters. A quick look in eicrecon shows "log" is 3rd in the list behind "dd4hep" and "acts". I'm not sure if it will solve the issue though by just switching these, but it might.

I have not tried building on macos even though I use it all of the time. Too many issues getting things running on Linux to worry about just now. I will try and get to it, but since I would need to compile all dependencies as well, it will be a while.

**Comment by veprbl** [comment]
The situation seems to have improved. Will file more specific issues/PRs.

**Comment by veprbl** [comment]
Or rather, everything is probably is still in a huge mess, but the hardcoded list of plugins is complete and properly ordered.
