### ISSUE TITLE
Default log level is not working

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#292]
On behalf of Zhongling Ji:

> I tried eicrecon -Peicrecon:LogLevel=error input.root, but there are still a lot of info and warning output. Did I do correctly?

Loggers clone themselves from the default logger, copying its level, but plugins use default value as info which overrides it.

**Comment by faustus123** [comment]
This was fixed in PR#307. Specifically for the calorimetry, but also globally in the ```log``` plugin. The ```eicrecon:LogLevel``` parameter should still set a global level that all factories inherit from. Individual factories can be set using <tag>:LogLevel where <tag> is the factory tag (i.e. collection name).

Closing this as fixed.

**Comment by DraTeots** [comment]
I also fixed LoggerMixin default level to be taken from logger service
