### ISSUE TITLE
Feature request: list available plugins

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#39]
This may already be possible or envisioned, but the usage instructions upon typing `eicrecon` do not include the infomation. How do I find out which plugins are available?

**Comment by faustus123** [comment]
I don't think we have something that programmatically does this at the moment. Plugins are searched for via the JANA_PLUGIN_PATH envar or (soon) the jana:plugin_path config. parameter. We should add the feature to list them.

**Comment by DraTeots** [comment]
If we talk about EICrecon, cmake does some reporting and it is relatively not that hard to add an ability to say, create a json/yaml list of built plugins. Even add a description. So I can imagine that after each CI there will be a list which could be used further. At the same time, one can "glob" .so files in plugin directory after the installation. Still, cmake is more reliable if to think about different edge cases. Let me know if this would work for now

If a user create her own plugin in a separate repository and installs it somewhere, then probably jana:plugin_path as David wrote probably is the solution. 

Some time ago we talked to Nathan that it would be good to scan through plugins creating a list of their parameters with their description. Which is also technically possible but require a couple of scripts

**Comment by DraTeots** [comment]
If what I've wrote would satisfy the need, assign this issue for me. Or please clarify more

**Comment by wdconinc** [comment]
I don't really care how it is done, but my request derives from the use case where someone wants to get started with EICrecon and types `eicrecon`. That quickly indicates the need for plugins, but the user doesn't know any plugins. So, e.g. `eicrecon -L` should list all possible plugins the user can specify with `-P`, along with all possible options for that plugin if `-v` is specified. If you need CI and a yaml file for that, then so be it.

**Comment by DraTeots** [comment]
Ok, now I understood what is needed!

**Comment by faustus123** [comment]
So the plugin list is fairly easy. The config. parameter list is not quite as trivial as one would think. We already have the -c,--configs option to jana (and eicrecon) which prints the existing config. parameters. We also have the -d,--dumpconfigs option which will write all of the parameters used in a job along with their values to a file. Due to the on-demand design structure of JANA though, many config. parameters do not exist until the point in which they are needed. Thus, printing a list of all possible ones is not possible without activating every type of event source, service, factory, and processor. The only other way to handle it would be to add a declaration system to JANA to allow these to be declared regardless of them ever being used. This breaks the paradigm a bit. We'll need to think about the best way to handle it since I agree that as a user, I would want such a list.

**Comment by DraTeots** [comment]
We actually thought about it with Nathan during ejana times. And some steps were done to achieve this. The task was not to get a plugins list, but get their arguments too. Basically there is a python script that activate plugins and gets their parameters from init(). It was working, but needs some polishing and testing after a couple of years of being dormant. I think we'll discuss how to be with its outputs. 

There was another interesting python script that collected README.md files from plugin directories and combine them into the documentation engine. And this approach in the end seemed actually better then the first one. But they certainly can compliment each other. So I'll do both of them. But it is not the high priority stuff before August 22 IMO

**Comment by faustus123** [comment]
The plugin list was introduced in PR #127 . One can get it by running `eicrecon --list-available-plugins`
