### ISSUE TITLE
Inconsistent include directives for non-EICrecon headers

### ISSUE THREAD

**Issue by c-dilks** [eic/EICrecon#729]
**Is your feature request related to a problem? Please describe.**
Not (yet) a problem, but we have inconsistent include directives for non-EICrecon headers, e.g.,
```cpp
#include <DD4hep/Detector.h>
```
vs.
```cpp
#include "DD4hep/Detector.h"
```

**Describe the solution you'd like**
What convention do we want to enforce here? Quotes for EICrecon headers and angle brackets for non-EICrecon headers?

**Comment by wdconinc** [comment]
I think we should address this, because it is potentially relevant in catching bugs. Right now we are building EICrecon inside a container that has EICrecon headers installed in a system include directory. So, `#include <algorithms/calorimetry/CalorimeterHitDigi.h>` fill find the system include before the local header, and only `#include "algorithms/calorimetry/CalorimeterHitDigi.h"` will find the local source tree header.
