### ISSUE TITLE
Add dependencies to RPATH by default?

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#842]
Users may reasonably expect that the configuring dependencies provides not just compile-time header paths, but also the runtime library paths https://chat.epic-eic.org/main/pl/qsa4ya8qdpb35cztq6z6csqu1y

We could support that by providing and enabling some support for RPATH(RUNPATH preferred?).

**Comment by wdconinc** [comment]
I'm working on this on the container side too. If we install EICrecon as all other packages, then we'll pick this up for free (since all spack packages are installed with rpath). It also has other benefits such as consistency (no dedicated build infrastructure in the container for just EICrecon) and better caching.

But we indeed need to support (and default to) rpath linking (and suitably adapted on macos too).

**Comment by wdconinc** [comment]
In the container we now use rpath for all EICrecon libraries and plugins.

**Comment by wdconinc** [comment]
Not quite closed. I think we want rpath linking for local installs too, right?

**Comment by wdconinc** [comment]
Fixed by #938
