### ISSUE TITLE
-PNThreads!=1 sometimes causes a crash

### ISSUE THREAD

**Issue by T-Britton** [eic/EICrecon#87]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): HEAD
- Any specific OS or system where the issue occurs? no
- Any special versions of ROOT or Geant4? no

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. run a plugin (maybe using the geometry) with -PNThread!=1
2. do that a few times to trigger a crash (usually a segfault of some kind)

### Expected Result: (what do you expect when you execute the steps above)
it not to crash

### Actual Result: (what do you get when you execute the steps above)
it crashes sometimes

**Comment by faustus123** [comment]
I confirmed that this is an issue. I see two problems:

1. it seems not all JANA threads are honoring jana:warmup_timeout since with multiple threads, I am getting timeout errors after 8 seconds and before 30 seconds. Setting jana:timeout to a larger number fixes this.

2. When timing out, a fatal error is printed and then the program proceeds to exit, but it ends up seg faulting in the end. Actually, there are multiple errors observed if run multiple times suggesting corrupted memory. The seg fault at the end is most often.

This can be reproduced in eic-shell with
~~~
eicrecon -Pnthreads=4 -Pjana_timeout=1 -Pplugins=EEMCcheck 2022-09-04_pgun_e-_podio-0.15_edm4hep-0.6_0-30GeV_alldir_1k.edm4hep.root
~~~

n.b. EEMCcheck can be found here: https://jeffersonlab-my.sharepoint.com/:u:/g/personal/davidl_jlab_org/EbsqzQgxJ5dPsDVr4hph5W4ByHf43wd6P04f6t81qk6OAA

the input file can be found here: https://eicaidata.s3.amazonaws.com/2022-09-04_pgun_e-_podio-0.15_edm4hep-0.6_0-30GeV_alldir_1k.edm4hep.root

**Comment by faustus123** [comment]
The thread timeouts are now increased when running eicrecon. This was introduced in PR#149.
